version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: farmtech_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: farmtech_db
      MYSQL_USER: farmtech_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: farmtech_app
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
    depends_on:
      - db

volumes:
  db_data: